# Generated by Django 3.2.9 on 2022-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220218_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
